export const user = [
    {
        id: 1,
        firstName:"Ayomide",
        surname: "Mamukuyomi",
        email:"ayomidemamukuyomi5@gmail.com",
        phone: "07016197076",
        password:"password",

    },
    {
        id: 2,
        firstName:"Emmanuel",
        surname: "Mamukuyomi",
        email:"ayomidemamukuyomi6@gmail.com",
        phone: "08024454940",
        password:"password",
    }
]

export const whoOwes = [
    {
        userId: 1,
        name: "Emmanuel",
        phone: "08024454940",
        notes:"",
        category:"you owe",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Mum",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Esther",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Fikayomi",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Xexes",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Esther",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Fikayomi",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 1,
        name: "Xexes",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Emmanuel",
        phone: "08024454940",
        notes:"",
        category:"you owe",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Mum",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Esther",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Fikayomi",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Xexes",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Esther",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Fikayomi",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
    {
        userId: 2,
        name: "Xexes",
        phone: "08024454940",
        notes:"",
        category:"owes you",
        amount: "5000",
    },
]